# Generated by Django 4.0.5 on 2022-07-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='car_list',
        ),
    ]
