# Generated by Django 4.0.5 on 2022-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_suppliers_car_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='car_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of cars for sale'),
        ),
    ]
