version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    command: bash -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "${PORTS}"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A car_dealership worker -l INFO
    env_file:
      - .env
    volumes:
      - .:/car_dealership


  celery-beat:
    build: .
    command: celery -A car_dealership beat -l info
    env_file:
      - .env
    volumes:
      - .:/car_dealership
    depends_on:
      - worker