# Generated by Django 4.0.5 on 2022-07-18 12:07

from django.db import migrations, models
import other.models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyerhistory_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='characteristics_of_car',
            field=models.JSONField(default=other.models.get_chars),
        ),
    ]
