# Generated by Django 4.0.5 on 2022-07-18 12:38

from django.db import migrations, models
import other.models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_buyers_characteristics_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='characteristics_of_car',
            field=models.JSONField(default=other.models.get_chars, verbose_name='Preferred Characteristics'),
        ),
    ]
