# Generated by Django 4.0.5 on 2022-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_buyeroffer_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeroffer',
            name='active_status',
            field=models.BooleanField(default=True, verbose_name='Offer status'),
        ),
    ]
