# Generated by Django 4.0.5 on 2022-07-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealertobuyer',
            name='car_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
