# Generated by Django 4.0.5 on 2022-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Time created')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Time edited')),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('engine_type', models.CharField(choices=[('diesel', 'Diesel'), ('gas', 'Gas'), ('hybrid', 'Hybrid')], max_length=30, verbose_name='Engine type')),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=30, verbose_name='Transmission type')),
                ('color', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('black', 'Black')], max_length=30, verbose_name='Color')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
